### ISSUE TITLE
Documentation or tools on pgr_withPoints

### ISSUE THREAD

**Issue by nahuelange** [pgRouting/pgrouting#1066]
### Expected behavior and actual behavior

For the moment, the documentation of pgr_withPoints family is mostly good. But all «points» steps are almost unusable, mainly first and last points of the route.
In the returned data, first and last seqs return a "point" on an edge, but doesn't return the direction to go on the edge and connect to the next one.
User have to calculate from the next (or previous) seq the substring that is needed, it's painful and time-waste.

Maybe I didn't find the good function to get the geometry from the result of a pgr_withPoints family function, in that case a bit more documentation could be great.
Else, improve the point's pgr_withpoints results or provide a function to return the geometry could be really useful for a lot of users.

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System
```
PostgreSQL 10.4 (Debian 10.4-2.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

POSTGIS="2.4.4 r16526" PGSQL="100" GEOS="3.5.1-CAPI-1.9.1 r4246" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.2, released 2016/10/24" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" TOPOLOGY RASTER
q

                pgr_version                
-------------------------------------------
 (2.6.0,v2.6.0,a6226c4,release/2.6,1.62.0)
```

**Comment by cvvergara** [comment]
@nahuelange 

* If the problem is geometries then its a PostGIS problem.
* I can say that The "same problem" happens with all the pgRouting functions.
* Unfortunately, having a " function to return the geometry" will make lots of applications slower, because, maybe you also want the name, so after getting the geometry you get the name, but within the same query you can get both. Or maybe you want the geometry, name & length (maybe you made you query based on time), and within the same query you can get all three data, instead of making one query for the geometry, and another query for the other data missing.
* This [How To](http://talks.vicky.georepublic.info/howto/flipGeometries.html) might be helpful on how to handle geometries & additional information in one query.

**Comment by nahuelange** [comment]
Hi,
Thanks for you answer and the howto. This howto shows how to retrieve geometries from pgr_dijsktra function, that return only edges. It's easy to merge those geometries. But in the case of pgr_withpoints family functions, the answer provides only points on a edge for first and last seq. 
In this example:
![image](https://user-images.githubusercontent.com/747262/42867185-1a5c7f08-8a6f-11e8-96f7-edc61c1dd484.png)

If the route is starting from 6(b) and going to 6(l), the answer will contain as first step « point 6(b) on edge 4(2,5) », don't you think it's painful to find if the geometry needed is «6(b),5», or «6(b),2)», as this information is not provided in the answer. Maybe I'm wrong or have a lack of informations, but the only way is to check the next seq, get the edge, and find the matching vertice to find the direction.

Anyway, thank you for all you job on pgRouting.

**Comment by cvvergara** [comment]
@nahuelange hi, use lag or lead to inspect the next row of the answer
