### ISSUE TITLE
Incorrect SSL configuration for www.pgrouting.org

### ISSUE THREAD

**Issue by sebastic** [pgRouting/pgrouting#1099]
The documentation in 2.6.1 was updated to use HTTPS for www.pgrouting.org among others, but SSL not configured correctly for the website. Firefox complains with:

> www.pgrouting.org uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, *.github.io, *.githubusercontent.com, *.github.com, github.com, github.io, githubusercontent.com Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by dkastl** [comment]
@cvvergara , I don't know really why this happens, because `www.pgrouting.org` should redirect to `pgrouting.org`, which is then managed through Github Pages, where I have only limited control.
It redirects correctly when you type http://www.pgrouting.org, but not when it's `https`.

I made some other redirect settings on the domain registrar's side, which does a different type of redirect. I hope, this doesn't cause other problems. It will take a bit to apply the changes.

**Comment by cvvergara** [comment]
@sebastic 
Did the fix work?

**Comment by sebastic** [comment]
No change yet.

You can test this yourself with:

 https://www.ssllabs.com/ssltest/analyze.html?d=www.pgrouting.org&hideResults=on

**Comment by sebastic** [comment]
How much control do you have over the Let's Encrypt certificate configuration?

The DNS contains a CNAME from www.pgrouting.org to pgrouting.org, and while the webserver supports both domain names, the SSL certificate only contains the pgrouting.org domain and is missing www.pgrouting.org in the `subjectAltName` field.

The Let's Encrypt configuration needs to include all domain names that are supported in the webserver configuration (e.g. the Apache ServerName value and all ServerAlias values). This is done by specifying all domain names in the `domains` option of the `certbot` configuration file for example.:
```
# Uncomment and update to generate certificates for the specified
# domains.
# domains = example.com, www.example.com
domains = pgrouting.org, www.pgrouting.org
```

Or using the commandline options:
```
certbot -d pgrouting.org -d www.pgrouting.org [options]
```

I don't know how SSL configuration works with GitHub pages, and if it doesn't support domain aliases for SSL certificates, you need to stop supporting www.pgrouting.org and only use pgrouting.org (e.g. how proj4.org works).

**Comment by dkastl** [comment]
@sebastic , thanks for the comment! I haven't been online yesterday and only tried to fix it with my mobile. I will need to look more into how Github does, because currently the website is hosted as Github Pages, and it just recently introduced HTTPS support for root domains. It seems they do use Let's Encrypt, but I have no control over how it's done.

I just read that changing www.pgrouting.org from a CNAME record to 301 redirect does not solve the problem, because it will still require a certificate for the `www` subdomain. I actually don't really understand why the CNAME record didn't work (anymore). I thought I had tested it long time ago and it worked, but I'm not sure anymore now.

In the worst case I will setup a redirect on a server, where I have control over the Let's Encrypt certificate generation. I just don't want to move away from Github Pagess, because it makes it easy for anyone with commit rights to deploy changes to the website.

**Comment by dkastl** [comment]
I think we have the same issue as described here: https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/td-p/7116

**Comment by dkastl** [comment]
With some delay, because a few things got in my way, I finally moved the name server to Cloudflare, which hopefully solved the problem with the certificate, if I interpret the result correctly here: https://www.ssllabs.com/ssltest/analyze.html?d=www.pgrouting.org&hideResults=on

Please reopen, if I was wrong.
