### ISSUE TITLE
Missing edges in DrivingDistance result

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#1198]
A user reports the following issue on Stackoverflow, where edges are missing in the DrivingDistance result: https://gis.stackexchange.com/questions/316812/lot-of-roads-are-missing-from-pgrouting-pgr-drivingdistance-result
It seems, that theyare missing when they are reached from two sides.

This reminded me, that I experienced a similiar issue some time ago with missing edges, and eventually this could be a hint to a bug.

TBD: Needs sample data/query to reproduce the issue.

**Comment by cvvergara** [comment]
From:
http://docs.pgrouting.org/2.6/en/pgr_drivingDistance.html#synopsis

> Using the Dijkstra algorithm, extracts all the nodes that have costs less than or equal to the value distance. The edges extracted will conform to the corresponding spanning tree.

"extracts all the nodes that have costs less than or equal to the value distance." So you get to the nodes within the driving distance

"The edges extracted will conform to the corresponding spanning tree."
The edges posted on the result are the ones that get you to the nodes within the driving distance.

So, say if G has nodes 1,2,3 and has edges 1->2 1->3 2->3 and for simplicity all edges have cost 2.
starting from node 1:
- Nodes within driving distance of 1: 1 with cost 0 and total cost 0 (no edge)
- Nodes within driving distance of 2: 1, 2, 3  edges involved on the spanning tree: 1->2 & 1->3
- Nodes within driving distance of 6: 1, 2, 3  edges involved on the spanning tree: 1->2 & 1->3 
Edge 2->3 is not missing because its not in the spanning tree of the solution.

**Comment by Komzpa** [comment]
Hello,

I need to infuse the result with all the edges that spanning tree touches. How do I do it?
