### ISSUE TITLE
pgr_analyzegraph - PGR ERROR wrong source type integer

### ISSUE THREAD

**Issue by JagDhillon** [pgRouting/pgrouting#1311]
### Expected behavior and actual behavior
Expected: pgr_analyzegraph() should not throw an error about type of column named source, when it is of type integer.

Actual: pgr_analyzegraph() does throw an error
![image](https://user-images.githubusercontent.com/13530017/69770868-5da52900-11d6-11ea-86d2-b1e96825c2fe.png)

### Steps to reproduce the problem
Run pgr_analyzegraph() where column type of source is integer

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System: WIndows 10 Home, 64 Bit

Use the commands:
```
SELECT version();
   PostgreSQL 11.5, compiled by Visual C++ build 1914, 64-bit
SELECT postgis_full_version();
   POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="110" GEOS="3.8.0-CAPI-1.13.1 " PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.9" LIBJSON="0.12" LIBPROTOBUF="1.2.1" WAGYU="0.4.3 (Internal)"
SELECT pgr_version();
   3.0.0-beta
```

### My Root Cause Guess
In my opinion, it seems pgr_analyzegrpah() does a case sensitive comparison when checking the type of the column i.e. it asserting that the type is 'INTEGER'.
This seems to be a bug. Type comparison should be case insensitive.

**Comment by cvvergara** [comment]
Hello @JagDhillon 

In order to reproduce the problem, we need:
1) `CREATE TABLE` statement that you use
2) some data that fills that table
3) the `SELECT` statement that you executed that gives that error.
4) Because of your description of case sensitive we need the query that works with only the change of case.
5) for all of the above (and in the future when reporting an error) please don't use images of code.
with images we can not copy/paste code or sections of the error code and discuss between us, or test the code.

**Comment by cvvergara** [comment]
@JagDhillon 
I figured out an example, and now I could verify your report
We are working on it.
Thanks for reporting
