### ISSUE TITLE
pgr_createtopology consumes all the system memory then crashes

### ISSUE THREAD

**Issue by mangecoeur** [pgRouting/pgrouting#1342]
### Expected behavior and actual behavior
Running `pgr_createtopology` on my road network data (about 2million line segments) consumes more and more memory until it runs out and crashes. My server has 128GB RAM and it gets to about  `180000 edges processed` before it consumes everything available and stops with an error like `Unexpected error could not resize shared memory segment "/PostgreSQL.1368262328" to 1048576 bytes: No space left on device`. 

I would have expected this process to use basically no RAM (i.e. write everything to disk)

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

PostgreSQL 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

POSTGIS="2.4.3 r16312" PGSQL="100" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.3, released 2017/11/20" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" TOPOLOGY RASTER

(2.5.2,v2.5.2,60585f1f7,master,1.65.1)

**Comment by dfwarden** [comment]
I ran in to this recently on a road network data table of about 1.09 million line segments and only 24GB RAM. I ended up having `pgr_createtopology()` go through my network table in chunks of 100k edges by id with something like:

`with starts as 
   (select generate_series as start_objectid from generate_series(0, 1090000, 100000) )
select 
   pgr_createtopology('edges_table', tolerance := 2, id := 'objectid', the_geom := 'shape', source := 'source', target := 'target', 
      rows_where := 'objectid >= ' || starts.start_objectid || ' and objectid <= ' || starts.start_objectid + 100000)
from starts;`

I'm wondering if it would've been better to iterate on slightly overlapping bounding boxes instead of edge id, but I'd have to dig in to the `pgr_createtopology()` code to know for sure. Based on the `pgr_createtopology()` behavior I've observed I believe this is an OK approach since in the "bad" case where two "touching" edges are handled by different calls to `pgr_createtopology()`, their intersection-within-`tolerance` should get the same vertex id in the created vertex table, and `pgr_analyzegraph()` afterwards should correctly calculate the `cnt` column of the vertices table.

Anyway, maybe this kind of approach would also work for you?

**Comment by LVerneyPEReN** [comment]
I was experiencing the exact same issue (on a graph of 40M edges, on a laptop with 12GB  RAM) and `rows_where` + computation by chunks of 1M edges is indeed passing fine.

Prior to coming across this issue, I had a look at the [`pgr_createTopology` source code](https://github.com/pgRouting/pgrouting/blob/b41c5639594bf577eea33b86fb34bac1a1a5515e/sql/topology/createtopology.sql#L259-L289) and it is not obvious to me where this memory consumption is coming from (compared to chunk computation). As far as I understand, the main edge processing loop is updated edges one by one, in a relatively stateless manner with respect to the rest of the graph? I'm even more surprised as the OOM I observed seems to be due to a very sudden allocation within the edge processing loop.


So, out of curiosity, I'm wondering if anyone with more familiarity with the code base had some insights on why the memory consumption of createTopology is so much dependent on the number of rows it is processing? Thanks!
