### ISSUE TITLE
Significant drop in performance when using new pgr_alphashape function

### ISSUE THREAD

**Issue by EPajares** [pgRouting/pgrouting#1345]
**Describe the bug**
Dear pgrouting-maintainers,

thanks first of all for your excellent work. I personally love pgrouting and I am using it frequently!
I am currently in the process of testing the pgr_alphashape function of the release pgrouting-3.0.0-rc1. 
When comparing the performance with the legacy function pgr_pointsaspolygon, that I am using in the release pgrouting-2.6.2 there are significant performance issues. I am not sure if this issue classifies as bug but I found no other appropriate category. 

**To Reproduce**

These are the queries that I am running:
Old version: 
`SELECT pgr_pointsaspolygon ('SELECT (row_number() over())::integer as id, ST_X(geom)::float x, ST_Y(geom)::float y FROM vertices',0.00003)`
![pgrouting2-alphashape](https://user-images.githubusercontent.com/42171996/78768933-eace6a80-798c-11ea-896d-4fad2d67d4e7.png)

New version:
`SELECT pgr_alphaShape((SELECT ST_COLLECT(geom) FROM vertices));`
![pgrouting3_alphashape](https://user-images.githubusercontent.com/42171996/78768950-f0c44b80-798c-11ea-9d3e-0700a6dcad44.png)

**Expected behavior**
Despite the fact that probably different alpha-parameters were used internally for the query in the new version compared to the query in the old version, I would not expect this drop in performance. 

**Sample Data**
I do have sample data for the table vertices. The data is identical, but there are two files in the folder because they are coming from different PostgreSQL version.

[sample_data.zip](https://github.com/pgRouting/pgrouting/files/4449618/sample_data.zip)

**Specifications**

Old version:
```
PostgreSQL 11.5
POSTGIS="2.5.1 r17027" 
pgrouting-2.6.2

Docker image: eliaspajares/goat-database:stable
```
New version:
```
PostgreSQL 12.2
POSTGIS="3.0.1 ec2a9aa" 
pgrouting-3.0.0-rc1

Docker image: goatcommunity/database:12-3.0.1-2.3.14-2
```
I would be very thankful for any help on this!

**Comment by cvvergara** [comment]
FYI:
This function should be part of PostGIS / GEOS  as its a geometry function.
And because of it it was adding an additional requirement for build pgRouting: CGAL

Please review the tests done for the release:
https://github.com/pgRouting/pgrouting/tree/master/pgtap/alpha_shape

Try to do similar tests for the 2.6 version. You will notice that, for 2.6 version, results are not good.
The geometry building that is generated is not what is expected for the benchmarks. The code on pgRouting around CGAL was not correct on the way to transmit the results.
Might be faster, as geometry specialists write CGAL, but unfortunately results are wrong, because of the C/C++/SQL code that is surrounding it. 

We are not going back to have CGAL as a dependency.

Performance VS Correctness

The  pgr_pointsAsPolygon in 2.6 might be fast but gives incorrect results, besides the fact that the name is totally misleading of what it actually does, because for example some PostGIS functions also convert points into polygons
- [ST_ConcaveHull](https://postgis.net/docs/ST_ConcaveHull.html) 
- [ST_ConvexHull](https://postgis.net/docs/ST_ConvexHull.html)

We actually want to move that function to GEOS that is the main PostGIS dependency.

**Comment by EPajares** [comment]
Thanks a lot for this answer! I understand. I agree that it should be part of PostGIS as it is something spatial. For now I might use ST_ConcaveHull or ST_Buffer.

**Comment by sanak** [comment]
@EPajares (CC: @cvvergara, @dkastl)
Well, I am interesting in this topic (even if GEOS + PostGIS (or Boost Geometry?) side support is preferable).
Let me check this issue (after finishing our company's current routing project task).

**Comment by dkastl** [comment]
CGAL was a dependency that always caused quite some extra effort for adding relatively little fucntionality. But since PostGIS uses CGAL now for a while (not sure about the details though), it probably just needs someone to contribute this function to PostGIS.

**Comment by sanak** [comment]
@dkastl Oh, yes. Moving the functionality to SFCGAL may be also good idea.
Here is past my thought.
https://lists.osgeo.org/pipermail/pgrouting-dev/2015-April/001525.html

**Comment by dkastl** [comment]
Oh, I didn't even remember this was a topic already in 2015 ;-)
Maybe @robe2 knows better if this would be possible/acceptable by PostGIS.

**Comment by EPajares** [comment]
@sanak Awesome that this is also interesting for you. Due to very little time I cannot work on it myself but I could do testing if desired.

**Comment by sanak** [comment]
@EPajares
Okay, no problem.
From glance of your community's system movie, the performance seems to be actually quite important factor. :)
https://www.open-accessibility.org/videos

**Comment by EPajares** [comment]
Hehehe yeah it is as we use it for live calculations :)

**Comment by robe2** [comment]
Just a heads up.  In PostGIS 3.3.0 ST_ConcaveHull is being done to use GEOS functionality.  This new version will be exposed for those running GEOS 3.11+ (not out yet).  postgis_sfcgal now also includes an AlphaShape.

Doc examples:
(there is still some work going in in [geos](https://github.com/libgeos) for polygons (and hopefully eventually linestrings), but the point support is pretty good from the bit I have tested.
[ST_ConcaveHull](https://postgis.net/docs/manual-3.3/ST_ConcaveHull.html)

The postgis_sfcgal [ST_AlphaShape](https://postgis.net/docs/manual-3.3/ST_AlphaShape.html) and [ST_OptimalAlphaShape](https://postgis.net/docs/manual-3.3/ST_OptimalAlphaShape.html) are based on the same CGAL logic as I think earlier pgRouting was.

If you happened to have a windows desktop or server, you can test our Windows CI bot builds (which contains not yet released GEOS, PostGIS, PostGIS_SFCGAL)  

Download https://postgis.net/windows_downloads/ in the Experimental section

**Comment by sanak** [comment]
@robe2 Okay, thanks for the useful information!

**Comment by cvvergara** [comment]
There is now postgis alpha shape
https://postgis.net/docs/manual-dev/ST_AlphaShape.html
