### ISSUE TITLE
pgr_road_dijkstravia search routes slow

### ISSUE THREAD

**Issue by Leijiawei** [pgRouting/pgrouting#1367]
I use pgr_road_dijkstravia to search routes,but very slow now.
I want to get help.
Thank you.

` 
EXPLAIN (analyze,buffers,verbose) select pt.geom FROM pgr_dijkstraVia(
'SELECT id, source, target, length as cost FROM road_all order by id',
array [89947,63660,48052,91204,21748],false,false,false) as di
join road_all pt
on di.edge = pt.id;
`

**Result**
Nested Loop  (cost=0.42..7958.00 rows=1000 width=101) (actual time=9446.040..9451.880 rows=333 loops=1)
  Output: pt.geom
  Inner Unique: true
  Buffers: shared hit=13905 read=23140
  ->  Function Scan on public.pgr_dijkstravia di  (cost=0.00..10.00 rows=1000 width=8) (actual time=9445.925..9446.013 rows=337 loops=1)
        Output: di.seq, di.path_id, di.path_seq, di.start_vid, di.end_vid, di.node, di.edge, di.cost, di.agg_cost, di.route_agg_cost
        Function Call: pgr_dijkstravia('SELECT id, source, target, length as cost FROM road_all order by id'::text, '{89947,63660,48052,91204,21748}'::integer[], false, false, false)
        Buffers: shared hit=12856 read=22845
  ->  Index Scan using road_all_pkey on public.road_all pt  (cost=0.42..7.95 rows=1 width=105) (actual time=0.016..0.016 rows=1 loops=337)
        Output: pt.id, pt.geom, pt."ID", pt."Kind_num", pt."Kind", pt."Width", pt."Direction", pt."Toll", pt."FuncClass", pt."Length", pt."DetailCity", pt."Through", pt."AdminCodeL", pt."AdminCodeR", pt."OnewayCRID", pt."AccessCRID", pt."SpeedClass", pt."LaneNumS2E", pt."LaneNumE2S", pt."LaneNum", pt."SpdLmtS2E", pt."SpdLmtE2S", pt."SpdSrcS2E", pt."SpdSrcE2S", pt."ParkFlag", pt."PHYLaneS2E", pt."PHYLaneE2S", pt."Shape_Leng", pt."PathName", pt."一级分类", pt.layer, pt.path, pt.source, pt.target, pt.length, pt.rev_length
        Index Cond: (pt.id = di.edge)
        Buffers: shared hit=1049 read=295
Planning Time: 0.375 ms
Execution Time: 9452.018 ms

**Comment by cvvergara** [comment]
The issue is on `pgr_dijkstraVia` we don't have a `pgr_road_dijkstraVia`
So separating the problem:
```
EXPLAIN (analyze,buffers,verbose) select pt.geom FROM pgr_dijkstraVia( 'SELECT id, source, target, length as cost FROM road_all order by id';
```
I deduce that is 9445.925 ms  = 9 seconds
```
 -> Function Scan on public.pgr_dijkstravia di (cost=0.00..10.00 rows=1000 width=8) (actual time=9445.925..9446.013 rows=337 loops=1)
```
I dont know the size of your data, and I can see that you load all the table, so I will make up a situation that represents a possible situation about your data:

`road_all` has all the road segments from Mexico:
- Going on a tour to Coyoacán
- traveling from Ensenada to Chichen Itzá

Just for rendering:

Load all the road segments? (trip from Ensenada to Chichen Itzá)
https://www.openstreetmap.org/#map=5/23.944/-102.579

Load only what is needed? (Going on a tour to Coyoacán)
https://www.openstreetmap.org/#map=16/19.3255/-99.1496

The same applies to pgRouting, maybe you are not limiting your graph to the area of interest which would be for the Coyoacán problem or maybe you are not limiting your graph the the kind of roads to be used, like use only Highways for the long trip to Chichen Itzá
