### ISSUE TITLE
FindDoxygen

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#2047]
Currently our build is not finding Doxygen to generate the developers documentation.

**Comment by sbdtu5498** [comment]
@cvvergara when I tried compiling pgRouting locally with the build_doxy option on, it was able to find the Doxygen and compile properly with the current CMake configuration file, but the real problem here was that no HTML folder was created. I tried different solutions that were available on the internet to build HTML pages with CMake and Doxygen but with no success. If there are some experiments that you did in the past while working on this issue, maybe some advice or a little bit of help, that would be great.

**Comment by cvvergara** [comment]
This is how the dependencies are installed:
https://github.com/pgRouting/pgrouting/blob/develop/.github/workflows/locale-and-website.yml#L54
The command to build the doxygen:
https://github.com/pgRouting/pgrouting/blob/develop/.github/workflows/locale-and-website.yml#L76
@krashish8 I cant find line for the update of the doxygen on the gh-pages.
and it still has 3.2 version on it.

**Comment by cvvergara** [comment]
@sbdtu5498 
When building doxygen you find the generated files in: `build/doxygen/html/`

**Comment by cvvergara** [comment]
I followed the code and we are finding Doxygen
https://github.com/pgRouting/pgrouting/blob/main/doxygen/CMakeLists.txt#L11
I'll mark the issue as invalid and close
