### ISSUE TITLE
pgr_ksp not finding any routes but pgr_dijkstra finds one for the same source and target

### ISSUE THREAD

**Issue by ccoffey** [pgRouting/pgrouting#207]
I believe there is a bug with pgr_ksp because it is not finding even a single route when pgr_dijkstra finds one for the same source and target pair.

This returns a route.

SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_dijkstra('
SELECT gid AS id,
     source::integer,
     target::integer,
     length::double precision AS cost
    FROM ways',
247542, 258349, false, false);

This returns nothing.

SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_ksp('
SELECT gid AS id,
     source::integer,
     target::integer,
     length::double precision AS cost
    FROM ways',
247542, 258349, 3, false);

Is this a bug?

**Comment by cvvergara** [comment]
This query that returns a route.
SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_dijkstra('
SELECT gid AS id,
source::integer,
target::integer,
length::double precision AS cost
FROM ways',
247542, 258349, false, false);

is equivalent to:

SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_ksp('
SELECT gid AS id,
source::integer,
target::integer,
length::double precision AS cost,
length::double precision AS reverse_cost
FROM ways',
247542, 258349, 3, false);

That is because Dijkstra has that extra flag, directed. When set to false it means undirected
to make your query in pgr_ksp, undirected, the same values in cost and in reverse_cost must be placed. 
That works also on Dijkstra, 
SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_dijkstra('
SELECT gid AS id,
source::integer,
target::integer,
length::double precision AS cost,
length::double precision AS reverse_cost
FROM ways',
247542, 258349, true, true);

**Comment by cvvergara** [comment]
@ccoffey 
Regardless of the equivalence query problem, when I executed the correct query, pgr_ksp, was caught in an endless loop.
Fixed with  commit 5cdd106ebe

**Comment by snow-abstraction** [comment]
@cvvergara I am looking through some ksp issues to get a feel for the pgrouting project. When I clicked on the commit link above that was supposed to have the fixed the problem, I found a commit that changes some tests. I expected some change to the ksp code. Did I miss something? Thanks

The page I came when clicking on the commit link was:
https://github.com/pgRouting/pgrouting/commit/5cdd106ebee79e9b216dceee4995ed5b7d87f996
