### ISSUE TITLE
pgr_trsp not fast enough at short distances

### ISSUE THREAD

**Issue by szilvesztererdos** [pgRouting/pgrouting#219]
I have read that the running time of the Dijkstra based algorithms at short distances (e.g. 0-10 km) is less with an order of several magnitudes than at large distances (e.g. 100-500km).
However, with pgr_trsp (or pgr_dijkstra) I cannot reproduce that. I experience that fetching the data for the function's first parameter takes the majority of running time and properly filtering those data is a difficult thing on a 5 million edge count graph.
With some kind of filtering I could reach a running time of several hundred milliseconds at short distances and one or max two orders of magnitude more at long distances but I think it can be much less. I feel somehow that something is wrong. It seems that there is a good and fast algorithm but when we plug it into Postgresql, then the whole data thing messes up everything.

Do you have a proper method for filtering the graph?
What running times do you have in different circumstances? What was the minimum?
Do I use the pgRouting functions wrong or it is normal behaviour?

Thanks in advance.

**Comment by cvvergara** [comment]
Work has been done for TRSP on develop branch for version 3.4 (due to be released on September/October 2022:
https://github.com/pgRouting/pgrouting/issues/2238
Please check the documentation
https://docs.pgrouting.org/dev/en/TRSP-family.html
and the migration guide:
https://docs.pgrouting.org/dev/en/trsp_migration.html

For further similar problems with TRSP functions please open a new issue with the specific function name
