### ISSUE TITLE
Add support for oneway streets to the driving distance code

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#233]
On 1/10/2014 3:20 AM, Necip Enes GENGEÇ wrote:
> Hi All,
> 
> Is there any chance that we can calculate the driving distances with 
> taking the one way both way situation as considered?
> 
> I am new at pgrouting. I can calculate with asuming my network is all 
> bothways but I could not find any information about the above mentioned 
> situation.

**Comment by woodbri** [comment]
@nagellette Is this still a problem for you or did the documentation resolve your issues?

**Comment by cvvergara** [comment]
Note to self
Some functions like:
pgr_apspJohnson, dont give the opportunity to set a cost different for going and comming
    By definition apsp only work on undirected graphs?
pgr-apsp-warshall: in the documentation mentions the flag but fails to mention dijktra like documentation. Is it because it applies to it? it doesn't apply to it? like "negative costs prevents the edge to be inserted".

pgr_dijkstra:  My comparison point, where weird things happen 
id, source, target cost, reverse_cost, false, true, will create 4 edges, because directed = false
source target cost
source target reverse_cost
target source  cost
target source  reverse_cost


pgr-astar:  similar to dijkstra
pgr-apsp-warshall: is not even implementing it:
https://github.com/pgRouting/pgrouting/blob/master/src/apsp_warshall/src/apsp_boost_wrapper.cpp#L61
bdAstar, difficult to follow code
bdDijstra  difficult to follow

**Comment by nagellette** [comment]
@woodbri yes it resolved.
