### ISSUE TITLE
VRP tests do not work because the results are random

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#248]
I have merged the gsoc-vrp branch into develop, but had to disable the tests for vrp because the results are always random so there is no way yet to compare the results to a standard.

**Comment by cvvergara** [comment]
The seed has a fixed value
https://github.com/pgRouting/pgrouting/blob/develop/src/vrp_basic/src/VRP_Solver.cpp#L241
He is picking a random truck here
https://github.com/pgRouting/pgrouting/blob/develop/src/vrp_basic/src/VRP_Solver.cpp#L313
To get consistent results it c could be solve just by picking up the first truck or the last truck index
instead of this:
int vehicleIndex = rand() % iUnusedVehicles--;
this
int vehicleIndex = iUnusedVehicles--;
And it is what is expected, because the seed is fixed.

**Comment by cvvergara** [comment]
I removed the bug report, the test for a function that uses a random must be designed better.

**Comment by cvvergara** [comment]
To be fixed
- [ ] pgr_gsoc_vrppdtw
- [ ] pgr_vrpOneDepot

**Comment by cvvergara** [comment]
Better design for testing: was done on version 2.3 for
pgr_gsoc_vrppdtw

**Comment by cvvergara** [comment]
Work was done on experimental functions for version 3.0
pgr_pickDeliver
pgr_vrpOneDepot
Closing
if new issue araises please open a new issue
