### ISSUE TITLE
Improve installation documentation

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#268]
It is possible that the pgrouting extension is dependent on have postgis installed as an extension rather then from the sql script. You can fix this with:

```
create extension postgis from unpackaged;
```

**Comment by cvvergara** [comment]
@dkastl 
Too much to ask what you meant on July 2014?
@robe2 
This has to do with postGIS, maybe you can give a hint.
I don't know how much @dkastl  comment has to do with the fact that:
postGIS doesn't have a line that requires its file to be added as an extension:
Doesn't have line like this:
```
\\echo Use \"CREATE EXTENSION postgis\" to load this file. \\quit
```
(at least not here):
```
$ more /usr/share/postgresql/9.3/extension/postgis--2.1.2.sql
```
and as you told me only when compiled with raster support is when postGIS is installed as an extension otherwise without raster support, postGIS its not installed as an extension.
(pgRouting doesn't need raster support, but we want to be installed as an extension)

**Comment by dkastl** [comment]
I think this is old. Probably at this time I had an issue with PostGIS, that wasn't installed as extension. But I don't remember details. `FROM unpackaged` is described here: http://dba.stackexchange.com/questions/58183/what-does-unpackaged-mean-in-postgresql-extensions

I don't think this is an issue anymore nowadays, so let's close this ticket.
