### ISSUE TITLE
Error installing PGRouting database extensions

### ISSUE THREAD

**Issue by ernestobaezf** [pgRouting/pgrouting#290]
Im trying to install pgRouting and I cannot reach the end of the way because of the following error:

    psql:/home/user/share/postgresql/contrib/pgrouting-2.0/pgrouting.sql:2459: 
    ERROR:  could not load library "/home/user/lib/postgresql/librouting_dd.so":
    libCGAL.so.10: cannot open shared object file: No such file or directory

I get this error when I try to apply extensions in postgres database by executing

    CREATE EXTENSION pgrouting

I installed the required dependencies and all installations were successful.
Im installing the application in a CentOS server and binaries are installend in 

    /home/user/lib
and

    /home/user/bin
librouting_dd is at:

    /home/user/lib/postgresql/librouting_dd.so
and cgal is at:
    
    /home/user/lib/libCGAL.so.10
 
To install the required dependencies and to install pgRouting I followed next steps:

::Installing Dependencies::

0. Navigate to tmp folder before start installing
	- cd $HOME/tmp
	- export TEMPDIR=$HOME/tmp

1. CMAKE
	- wget http\://www.cmake.org/files/v3.1/cmake-3.1.2.tar.gz
   	- tar xzf cmake-3.1.2.tar.gz
   	- cd cmake-3.1.2
   	- ./bootstrap
   	- make --prefix=$HOME
   	- make install

2. BOOST
	- wget http\://sourceforge.net/projects/boost/files/boost/1.57.0/boost.tar.gz
	- tar xzf boost.tar.gz
	- cd boost_1_57_0/
	- ./boostrap.sh
	- b2 install --prefix=$HOME

3. MPFR
	- wget http\://www.mpfr.org/mpfr-current/mpfr-3.1.2.tar.gz
	- tar xzf mpfr-3.1.2.tar.gz
	- cd mpfr-3.1.2/
	- ./configure
	- make
	- make check
	- make install

4. CGAL
	- wget https\://gforge.inria.fr/frs/download.php/file/34400/CGAL-4.5.1.tar.gz
	- tar xzf CGAL-4.5.1.tar.gz
	- cd CGAL-4.5.1/
	- cmake .
	- make
	- make install

::Installing PGRouting::

1. Download package
	- git clone git\://github.com/pgRouting/pgrouting.git 
	- cd pgrouting

2. Install package
	- mkdir build
	- cd build
	- cmake -DBoost_NO_BOOST_CMAKE=ON ..
	- make
	- make install

**Comment by woodbri** [comment]
First, (I don't use Gentoo), but /home/user/ does not look like a good place to install these. I would think that they should be getting installed in /usr/local/ 
Second, the system can not fine libCGAL.so.10, probably because you have not installed is as a system library. At a minimum, you probably need to add that locations to /etc/ld.so.conf or in a file in /etc/ld.so.conf.d/

**Comment by ernestobaezf** [comment]
Im installing this library in a webfaction server so I dont have access to /usr/local/ and /etc/ld.so.conf neigther to super user access. It would be preferable to install it in my side. Is there a way to do that?

**Comment by dkastl** [comment]
pgRouting uses CMake and there is `FindCGAL.cmake` to manage CGAL installation: https://github.com/pgRouting/pgrouting/blob/master/cmake/FindCGAL.cmake

I think there is also a way to override paths as CMake command line options, but I don't remember how this works. Though you could try to add your paths to `FindCGAL.cmake`.

**Comment by woodbri** [comment]
I'm not sure that you can do this as a regular user. Are you running the database as your user or is it running as a system service? You will probably need to run this in a VM where you have root access.

**Comment by ernestobaezf** [comment]
Sorry, but I dont know how to use the FindCGAL.cmake file suggested by dkastl. Can you help me please?
In the other hand I have a postgresql server version 9.3 installed and a postgis v2.0 in my home and running using supervisor (http://supervisor .org), I dont use superuser privileges to run it.
As an additional comment I would like to say that I dont think the issue si due to CGAL, I think that the problem is that CGAL does not find the path to librouting_dd.so. I dont understand why it does not find the path and put the full path in the error message. As I mentioned all the apps were installed without errors or warnings. This seem very strange to me.

**Comment by woodbri** [comment]
FindCGAL.cmake is not the problem, you can ignore that.

When a library is install, like librouting_dd.so, then runtime loader needs to find all if the dependencies like libCGAL.so.10 and make links between the library and its dependencies. This only happens when you try to run it. I have never run supervisor, so you might have an issue with the way it is configured, Or there might be a problem with differences between your build system and you runtime system.

Regardless, this is NOT a pgRouting problem so I'm closing this. You should check with the supervisor mailing list. Also questions like this should be put on the pgrouting-user or pgrouting-dev list rather than a bug report.

**Comment by woodbri** [comment]
Correction for future reference: http://supervisord.org/
