### ISSUE TITLE
pgr_texttopoints

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#311]
Referring to #309 we should rename `pgr_texttopoints` to `_pgr_texttopoints` and provide a wrapper (returning a notice) to ensure backwards compatibility.

**Comment by cvvergara** [comment]
I made some pgTap tests based on the documentation
```
../../src/convinience/test/pgtap/textToPoints-types-check.sql ..... 1/2 
# Failed (TODO) test 2: "Function pgr_texttopoints(text, integer) should return integer"
#         have: geometry[]
#         want: integer
```

**Comment by cvvergara** [comment]
The reason for this function to exist is pgr_tsp V2.0, 2.1, 2.2 signatures as a preprocessing function where the results are given as a parameter to pgr_tsp.
This pgr_tsp signatures are going to be deprecated on V2.3 and for new different signatures where:

pgr_eucledianTSP does not need a matrix
pgr_tsp, the matrix is given as a postgres set query instead of an array (see #368 (comment) about large arrays)

So, this function are being deprecated together with the pgr_tsp deprecated signatures.
They will remain on the project during the 2.x versions for backwards compatibility.

Currently
* Internally it is used in a deprecated function: pgr_pointstodmatrix as a parameter
* There is ahttp://postgis.net/docs/ST_GeomFromText.html
* And a  http://postgis.net/docs/ST_PointFromText.html
