### ISSUE TITLE
Consider making develop the default branch on github

### ISSUE THREAD

**Issue by aaronc** [pgRouting/pgrouting#348]
I understand you may be using a gitflow workflow, but by leaving master as the default branch on github makes it look as if your project hasn't been active for 2 years when that clearly isn't the case. Developers who take a quick glance might write the project off as inactive...

**Comment by woodbri** [comment]
done.

**Comment by cvvergara** [comment]
@aaronc I appreciate your comment.

**Comment by aaronc** [comment]
You're welcome. Have run into the same issue with my projects...

**Comment by dkastl** [comment]
@aaronc Thank you for your comment. I know about the possibility to change the default branch, but I kept `master` as default, because I think there are also reasons not to make `develop` the default branch.  For example it will prevent, that inexperienced users checkout the develop branch not being aware, that it is not a stable version.

My assumption was, that experienced users will usually know about other branches and will find out about `develop`. Maybe a comment in the Readme file would be helpful, too.

So I'm not really against making `develop` the default branch for Github, but I'm not sure it's really a good idea.
