### ISSUE TITLE
Emtpy result vs result with one row that has -1 to indicate no result found

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#353]
I am opening this issue, based on @boerngen-schmidt comment in #349
```
pgr_dijkstra(text sql, bigint start_v, bigint end_v, boolean directed:=true);
   RETURNS SET OF (seq, node, edge, cost, tot_cost) OR EMTPY RESULT
```
What is best for the user's:
empty result
or
result with one row with -1 (this is the current implementation)

I am labeling as 2.1 where:
For pgr_dijkstra, pgr_ksp, and pgr_driving distance would be fast to modify to empty result.

**Comment by woodbri** [comment]
The row with -1 does not indicate empty result it indicates end of path. End of path might also indicate empty result if there were not preceding lines. There are two issues where this is needed:

1. with the result set (seq, node, edge, cost, tot_cost) you need to extra record to hold the tot_cost
2. when you have an algorithm that returns multiple paths in addition to 1. it is also easier to check for a -1 than a change in path number to determine where one path stops and the next starts.

While you can make a case that some functions do not need this, we decided that it made more sense for all functions to be consistent because once a user developed a tools to parse one function set of results that could be applied to others also, rather than needing a tool for each different function and needing to remember which tool when with which function.

Look at the results of all functions and you will see that they fall into an abstraction based on the number of columns required to represent the result. and there are only 3-4 function return types where there used to be many more.

**Comment by cvvergara** [comment]
What is the possible representation of no path found:
In sample data there is no route from 1 to 17 (17 is in a disconnected edge from the rest of the graph)
Possible scenarios,  
- the data needs to be nodded.
- the user didn't put enough data to find a path
- For directed graphs, for example, when the target node does not have incoming edges or the source vertex does not have outgoing edges.

``` 
select * from pgr_dijkstra('select * from edge_table', 2, 17);
```
option (1)
```
 seq | node | edge | cost | tot_cost 
-----+------+------+------+----------
(0 rows)
```

option (2)
```
 seq | node | edge | cost | tot_cost 
-----+------+------+------+----------
   0 |   -1 |   -1 |    0 |        0
(1 rows)
```
option (3)
```
 seq | node | edge | cost | tot_cost 
-----+------+------+------+----------
   0 |   2 |   -1 |    0 |        0
(1 rows)
```
option (4)
```
Error: No path not found, (with a meaninful message like: please check your topology, add more edges, or make your graph undirected)
CONTEXT:  PL/pgSQL function pgr_dijkstra(text,bigint,bigint) line 7 at RETURN QUERY
```

**Comment by woodbri** [comment]
To recap our discussion, I think that we as developers need to look at pgrouting in terms of a product and not in terms of this function or that function or this or that issue. What I mean by this is that we need to be aware of how all functions are behaving and what they are returning and be consistent across all of them. For example, whatever we decide is the model for any one function to indicate the end of a path or an empty path, we need to consider how that works in other functions the return paths so the model is consistent across the product.

We often get requests from users and many of these are framed as a solution to some problem they are having. We need to understand the problem in the context of the product and can we find a solution that is consistent with the product, or does the issue represent a fundamental flaw in the modelling of the product, or is it an enhancement/change to the product model, or is it user error; ie: trying to get the product to do something it was not intended to do or not using it correctly.

For example, in pgRouting 2.0, all functions that return a path return one of the following three record structures: http://docs.pgrouting.org/2.0/en/src/common/doc/types/index.html  While this does not discuss error returns or empty paths, it is the fundamental model the all functions adhere to.
One of the reasons for these abstract types, is to make it easy to post-process the results. Say you want to create a driving directions module as an example of post-processing, it is convenient to have all the input data to to this module be of the same type regardless of the function that was used to compute it. Otherwise we have to deal with multiple input record types based on whatever random function was used to generate the path results that you want to post-process.

Maybe we need functions that can cast one result set into another?

Another use case might be to determine which pairs of a many to many Dijkstra are NOT routeable? If we have a record as a placeholder for each route then it is easy to identify those that are not routeable, but if I have to look for the absence of a record, then I have to figure out a more complex SQL that generates all the possible pairs and left outer joins with the results and look for the null joined records.

**Comment by woodbri** [comment]
https://github.com/pgRouting/pgrouting/wiki/Uniform-Result-Set-for-pgr_dijkstra%28%29-in-3.0

**Comment by cvvergara** [comment]
I dont understand how we got from the how to represent no result/path to change of names?

**Comment by woodbri** [comment]
The names don't need to change if the functions all use a common result set. But if you want to maintain the function specific result sets, then a simple wrapper with a new name can be used to accomplish this.

**Comment by dkastl** [comment]
My first thought is: if you `select` something that is empty, then it should be "no rows" ... that's what I would expect from SQL.

**Comment by dkastl** [comment]
To continue the previous idea:
pgRouting's functions should be written in a way, that the result can be used as input for new queries. For example you may want to join the results with the original table. So if there is no result, then a join should be also empty.

**Comment by cvvergara** [comment]
I like option (1), no path found is with empty set (of course that menas I need to code that), but do we need to change the name of the function to be something like:  pgr_dijkstra_UNI ???

**Comment by woodbri** [comment]
> but do we need to change the name of the function to be something like: pgr_dijkstra_UNI ???
Now you are just being silly, why would anyone want to do that?

**Comment by cvvergara** [comment]
I didnt say you were being silly?
Maybe I misunderstood this:
https://github.com/pgRouting/pgrouting/wiki/Uniform-Result-Set-for-pgr_dijkstra%28%29-in-3.0

**Comment by Zia-** [comment]
I agree with @woodbri regarding functions structure's consistency.
But I have following remarks
1. Undirected graph: If the routing query is coming out empty then there is a high possibility that some edge is broken (since most of the time the underlying data is osm which is not fool-proof). I think somehow it must be informed to the user, via sql output or I dunno what, to fix that broken edge.
2. Directed graph: As a user I would like to know which edge is one-way so that I can alter my query accordingly.
In any scenario, user must get an `information` to know what has happened in the graph and why my result is empty. Otherwise there could be many reasons for `empty result`.
Although empty results will assist users (willing to deploy routing services over web) handling `sql views` in geoserver and will help during sql joins also but I guess we can deal those kind of situations using 'sql case condition'.
I personally had hard time fixing `empty result` output.

**Comment by woodbri** [comment]
There are multiple issues here and they are related. Ultimately the end result needs to be considered in context of the product as a whole. It is easy to say the no result should be empty result or more correctly no result because that is what we expect from a simple query, but it might not be the correct answer for a more complex query. It is also easier to filter out an empty result return by a -1 placeholder record than it is to determine which records failed to return results by determining the absence of their records in the return set.

Issues under discussion:
  1. what does the -1 record mean?
    * end of path indicator ( this is its meaning in pgrouting 2.0 )
    * no result ( this is not the meaning in pgrouting 2.0 )
  2. consistency or abstraction of return types

Item 1. is one aspect of item 2. but item 2 also needs to consider things like https://github.com/pgRouting/pgrouting/wiki/Uniform-Result-Set-for-pgr_dijkstra%28%29-in-3.0 , consistent naming of return columns, and result structures so it is easy to write reusable post-processing function.

**Comment by dkastl** [comment]
I'm totally for consistency ... but I only thought about this particular case now.

Just another (maybe strange) thought: if we discuss about the meaning of `-1` now, could it be that we need such a strange value because we did it wrong all the time? 
Now we return a set of nodes, but maybe we better return a set of edges, because that's what we select from the database. We also want to show edges later as result, don't we? Even for DD we better had edges as result and not nodes.

So could it be, that we return a list of nodes (with edge ID's as attributes), because it's close to what Boost returns? If we return edges, then we don't need `-1` at all.

**Comment by dkastl** [comment]
How a result with edges could look like:
```
pgr_dijkstra(text sql, bigint start_v, bigint end_v, boolean directed:=true);
   RETURNS SET OF (seq, edge, direction, cost, tot_cost) OR EMTPY RESULT
```

With `direction` (not a good term maybe) we indicate if the edge is traversed from source to target or the reverse direction.

I think it makes much more sense to return edges, because most attributes are edge based: street name, length, traversal time, geometry, ... and we never have to care about `-1`, because the last record is the last edge. And if there is no row returned, then there is no path.

**Comment by cvvergara** [comment]
(There is no support on the current code in any of the functions (2.0 or 3.0) for "direction", but we can open a discussion issue about that.)

So, going back a little to the origin of this discussion issue:

```
pgr_dijkstra(text sql, bigint start_v, bigint end_v, boolean directed:=true)
   RETURNS SET OF (seq, node, edge, cost, tot_cost) OR EMTPY RESULT
```

To generalize id of what the issue is about.

```
pgr_foo(text sql,  <rest of parameters>)
   RETURNS SET OF ( seq, ....  ) OR EMTPY RESULT
```
when no path is found is consistent with.
```
 seq | .....
-----+------+------+------+----------
(0 rows)
```
and also consistent on the way postgres handles things when there is no result, (it returns 0 rows).


I think that:
option (4)
```
Error: No path not found, (with a meaninful message like: please check your topology, add more edges, or make your graph undirected)
CONTEXT:  PL/pgSQL function pgr_dijkstra(text,bigint,bigint) line 7 at RETURN QUERY
```
is not good, because "Error" implies that the code has an error. The algorithm, based on the input data finds the shortest path, if any.
The user has other tools to analyse before calling the function that his topology is correct, which edges are one way, that he included the sufficient and reasonable edges that can throw a solution if any, that the starting_id is in the edges list, that the ending_id is also in the edges list etc.

**Comment by dkastl** [comment]
With "direction" I only want to distinguish if the route is from source to target or from target to source.

**Comment by Zia-** [comment]
@dkastl so basically you are saying to replace nodes column with direction column. although they are serving the same purpose i.e. to show the direction. 
Pros: user will get as much rows as there are edges. Coz till now we were getting the very last row unnecessarily. That makes more sense.
Cons: user may run into trouble in order to decipher the reason behind empty result. or may be sql error codes may be improved to deal with possibilities regarding empty result.
@cvvergara you mentioned about some analysis tools for graph. Is there any tool to locate broken edges?

**Comment by woodbri** [comment]
@Zia- the purpose of routing tools is to generate a route if it is possible and not to analyze the graph and report problems. Either a route is possible or it is not. There are many reasons why it might not be possible to generate a route. Dijkstra and friends work by converting the graph into a tree based on the source node and then look for the target node in the tree. If it is found in the tree then you have a path from source to target, but if the target node is not in the tree then there is no path. There is no way to answer the question why is my target not in the tree.

Some possible reason why it might not be there:
1. the source and target are in disconnected sub-graphs, think of an island with no bridge connecting it to the mainland
2. Some combination of oneway streets is preventing access to the target
3. there are serious problems with the topology
4. the data is not properly noded
5. if you are working with zlevel information at intersections this could be broken
6. some turn restrictions might be broken

What is a broken edge? How would you identify it? If you are thinking about a tool like ESRI graph assistant than you need to develop commands the analyze these and other potential problems and report them in some intelligent way to assist the user in fixing these problems.

**Comment by woodbri** [comment]
@dkastl Changing the result type from node based to edge based makes sense to me, but I think this has to wait for 3.0 and not 2.1. It is still a mind-bender on how to get a list of the routes that failed.

```
select * from pgr_dijkstra(sql, array[1,2,3,4], array[101,102,103], ...);
```
is a many to many result and should generate up to 12 resulting paths, but lets say two of the paths failed 2-103 and 4-101. *How to I get the list of failed routes? *

If there were a placeholder record then with tot_cost=-1 then these simple queries work:

```
-- get the valid results
select * from pgr_dijkstra(sql, array[1,2,3,4], array[101,102,103], ...) where tot_cost>0;

-- the failed routes
select * from pgr_dijkstra(sql, array[1,2,3,4], array[101,102,103], ...) where tot_cost<0;
```

If you remove the placeholder, what is the equivalent SQL to get the failed routes?

**Comment by dkastl** [comment]
@woodbri Yes, this is a major change, so nothing for 2.1. I just had the idea because we started discussing about what -1 means. I think we carry around several things from the past, that we take granted. 

@Zia- an empty result is not an error for me. It's a valid result. There is just no path between two points, which could be even the intent of a query, if you want to test for disconnected networks. So I wouldn't say there should be better error handling for empty result, because it's not an error. Do you agree?

**Comment by dkastl** [comment]
@woodbri You ask what to do with empty results for multiple shortest path queries in one query.
Let's say, if we have have the 12 resulting paths as in your example, maybe we need to return start as well as end ID as attribute, so missing paths would also miss start/end attribute.

**Comment by woodbri** [comment]
@dkastl They already are missing the start and end attribute because they are not in the result set, I don't think that is going to help. My point is that there are two use cases, 1) getting the valid routes, and 2) getting the list of failed routes. Any Jedi master of SQL can get the 2) results but most of our users are not Jedi masters. You should construct the query to get the list of the missing routing so you understand how hard it is to generate even for someone with reasonable knowledge of SQL. It is reasonably trivial for us to generate the place holder records in the C/C++ code but is is not easy to reconstruct them from the results in 1) and if the placeholders for the failed routes exist, it is trivial to filter them if you don't want them or to select only them if that is all you need.

**Comment by woodbri** [comment]
So I tried to write this SQL, and I'm not sure I can do it without writing a complex plpgsql function. Assuming the we were doing it based on edges and the return result include columns source, target as you indicated we might want to include this is the best I could come up with, without a lot more thought.
```
select foo.source, foo.target from
  (select a.id as id1, b.id as id2 from
     (select unnest(array[1,2,3,4]) as id ) a,
     (select unnest(array[101, 102, 103]) as id ) b
  ) as foo
  left outer join
  (select * from pgr_dijkstra(edges, array[1,2,3,4], array[101, 102, 103], ...)) as bar
  on foo.source=bar.source and foo.target=bar.target
  where seq is null;
```
this might be simplified a little by putting the two arrays in a CTE and then referring to the those rather than repeating them.

Anyway, no matter what the answer is, it is WAY more complicated for the users and it is trivial to work with the placeholders.

**Comment by cvvergara** [comment]
Some examples using the sample data of the documentation:

There are paths from 2 to 5, from 2 to 5, from 7 to 5 and from 7 to 6. 

```
select * from pgr_dijkstra( 'select id, source, target, cost from edge_table',
     array[2,7], array[5,6]);
 seq | start_v | end_v | node | edge | cost | tot_cost 
-----+---------+-------+------+------+------+----------
   0 |       2 |     5 |    2 |    4 |    1 |        0
   1 |       2 |     5 |    5 |   -1 |    0 |        1
   2 |       2 |     6 |    2 |    4 |    1 |        0
   3 |       2 |     6 |    5 |    8 |    1 |        1
   4 |       2 |     6 |    6 |   -1 |    0 |        2
   5 |       7 |     5 |    7 |    6 |    1 |        0
   6 |       7 |     5 |    8 |    7 |    1 |        1
   7 |       7 |     5 |    5 |   -1 |    0 |        2
   8 |       7 |     6 |    7 |    6 |    1 |        0
   9 |       7 |     6 |    8 |    7 |    1 |        1
  10 |       7 |     6 |    5 |    8 |    1 |        2
  11 |       7 |     6 |    6 |   -1 |    0 |        3
(12 rows)
```

There are no paths from from 2 to 17,  from 7 to 17,  from 2 to 18 and from 7 to 18.
Returning empty set because there is no path in any of the combinations.
```
select * from pgr_dijkstra( 'select id, source, target, cost from edge_table', 
    array[2,7], array[17,18]);
 seq | start_v | end_v | node | edge | cost | tot_cost 
-----+---------+-------+------+------+------+----------
(0 rows)
```


The both of the above in one call. Mathematically speaking we are making a Union of the two resulting sets.

```
select * from pgr_dijkstra( 'select id, source, target, cost from edge_table', 
array[2,7], array[5,6,17,18]);
 seq | start_v | end_v | node | edge | cost | tot_cost 
-----+---------+-------+------+------+------+----------
   0 |       2 |     5 |    2 |    4 |    1 |        0
   1 |       2 |     5 |    5 |   -1 |    0 |        1
   2 |       2 |     6 |    2 |    4 |    1 |        0
   3 |       2 |     6 |    5 |    8 |    1 |        1
   4 |       2 |     6 |    6 |   -1 |    0 |        2
   5 |       7 |     5 |    7 |    6 |    1 |        0
   6 |       7 |     5 |    8 |    7 |    1 |        1
   7 |       7 |     5 |    5 |   -1 |    0 |        2
   8 |       7 |     6 |    7 |    6 |    1 |        0
   9 |       7 |     6 |    8 |    7 |    1 |        1
  10 |       7 |     6 |    5 |    8 |    1 |        2
  11 |       7 |     6 |    6 |   -1 |    0 |        3
(12 rows)

**Comment by cvvergara** [comment]
@dkastl about your comment:
"Let's say, if we have have the 12 resulting paths as in your example, maybe we need to return start as well as end ID as attribute, so missing paths would also miss start/end attribute."

In my last comment, you can see an example of how V3 signatures:

  1. the names are more meaningful,  (easy to change to id1, id2, id3, id4 if you want)
  3. there is a start_v and end_v returning attributes and the missing paths don't show up
  2. the missing paths also dont show in the start_v, end_v columns combination
  4. Automatically detection of what kind of Dijkstra just by checking the functions arguments. (no new name to remember)
  5. No paths returns no rows (empty set) and is congruent with what postgres does when no result is found. 
  6. The unseeing parts:
    -  is that the id's can be smallint, int, bigint (for V2, only integer is allowed)
    -  for cost and reverse-cost:  smallint, int, bigint, real, float (in V2 only float is allowed)
    -  for the many to 1, many to many, and 1 to many, Load the graph once, and calculate all combinations asked.

**Comment by Zia-** [comment]
@woodbri Many times because of users negligence (during OSM editing) we observe road sections (edges) which must be connected to other road sections starting or ending nodes but are not and floating independently in the graph. I am referring to them as `broken edges`. Since we can fix this problem to make our graph more mature, I was giving it a thought to assist users to locate them. But apologies to miss understood the core purpose of routing tools.

@dkastl It makes proper sense what you are recommending. It was my bad to understand the scope of routing tools.

**Comment by Zia-** [comment]
Just a crude idea. Apologies if I went silly.
Let me summarize the problems if I understood them correctly.

1. When running algorithm that returns multiple paths, how to know when the new route combination has started. Like after combination 2-6, the start of 7-5 combination in the example above by @cvvergara.
2. How to figure out those combinations for which there is no possible route.
3. How to show the output when there is no possible route while running route algo. only one set of nodes. Means some output vs empty result?

I would like to extend the idea of @dkastl by introducing one more column (`Boolean reached`) which could assist user to understand the scenario.

`pgr_dijkstra(text sql, bigint start_v, bigint end_v, boolean directed:=true);
   RETURNS SET OF (seq, start_v, end_v, edge, direction, cost, tot_cost, reached)`

This new reached column (could be a better name) will check if the end_v is lying on the corresponding edge in a row. So basically the moment we will reach to the final edge in a particular route scenario, the reached boolean will turn out to be 1. 

Now consider the following example where there are no paths from 2 to 17, from 7 to 17, from 2 to 18 and from 7 to 18. I am considering direction column also to be boolean i.e. 1 if the route is from source to target and vice versa.

`select * from pgr_dijkstra( 'select id, source, target, cost from edge_table', 
array[2,7], array[5,6,17,18]);
 seq | start_v | end_v | edge | direction | cost | tot_cost | reached
-----+---------+-------+------+------+------+----------
   0 |       2 |     5 |    400 |    1 |    1 |        1        |    1
   1 |       2 |     6 |    101 |   0 |    1 |        1        |    0
   2 |       2 |     6 |    102 |   1 |    1 |        2        |    0  
   3 |       2 |     6 |    103 |   1 |    1 |        3        |    1 
   4 |       2 |     17 |    -1 |   1 |    0 |        1        |    1
   5 |       2 |     18 |    -1 |   1 |    0 |        1        |    1
   6 |       7 |     5 |    300 |   1 |    1 |        1        |    0  
   ...................
   ...................
   Ans so on
(rows are manually generated)`

Following are my remarks regarding above approach.

Pros:
    1. To check if there is no route possible for a given combination check the corresponding edge value for -1 (row 4 and 5 above). One can even count also the number of rows with -1 edge values to know how many route combinations are not possible.
    2. To count the total number of route combinations from a multiple routing query, count the total number of rows with reached column value 1. Check also reached column value 1 for the start of a new combination (check row 3 to 4 above).
    3. While running only one combination (lets say 5-10), if there is no possible route the result will be somewhat similar to this
    `seq | start_v | end_v | edge | direction | cost | tot_cost | reached
-----+---------+-------+------+------+------+----------
   0 |       5 |     10 |    -1 |    1 |    0 |        1        |    1`
     To deal with condition stated by @dkastl `For example you may want to join the results with the original table.`, one can easily run a basic SQL like `insert into original_table select * from pgr_djikstra(...) where edge != -1`.
    4. Generating reached column should be easy as all we have to check is if the end_v is either the source or the target value of corresponding edge in a row.
    5. Total number of rows will be the total number of edges in a particular route. Unlike -1 placeholder which was consuming one additional last row unnecessarily.

Cons:
    1. I have no idea regarding limitations and possibilities when it comes to real coding. So pardon me.

You are free to completely discard my idea for some logical reasoning.

**Comment by Zia-** [comment]
Just a crude idea. Apologies if I went silly.
Let me summarize the problems if I understood them correctly.

1. When running algorithm that returns multiple paths, how to know when the new route combination has started. Like after combination 2-6, the start of 7-5 combination in the example above by @cvvergara.

2. How to figure out those combinations for which there is no possible route.

3. How to show the output when there is no possible route while running route algo. for only one set of nodes. Means some output vs empty result?

I would like to extend the idea of @dkastl by introducing one more column (Boolean reached) which could assist user to understand the scenario.

    pgr_dijkstra(text sql, bigint start_v, bigint end_v, boolean directed:=true); 
    RETURNS SET OF (seq, start_v, end_v, edge, direction, cost, tot_cost, reached)

This new reached column (there could be a better name) will check if the end_v is lying on the corresponding edge in a row. So basically the moment we will reach to the final edge in a particular route scenario, the reached boolean will turn out to be 1.

Now consider the following example where there are no paths from 2 to 17, from 7 to 17, from 2 to 18 and from 7 to 18. I am considering direction column also to be boolean i.e. 1 if the route is from source to target and vice versa.

    select * from pgr_dijkstra( 'select id, source, target, cost from edge_table', array[2,7], array[5,6,17,18]); 
    seq | start_v | end_v | edge | direction | cost | tot_cost | reached
    -----+---------+-------+------+------+------+----------
    0 | 2 | 5 | 400 | 1 | 1 | 1 | 1
    1 | 2 | 6 | 101 | 0 | 1 | 1 | 0
    2 | 2 | 6 | 102 | 1 | 1 | 2 | 0 
    3 | 2 | 6 | 103 | 1 | 1 | 3 | 1 
    4 | 2 | 17 | -1 | 1 | 0 | 1 | 1
    5 | 2 | 18 | -1 | 1 | 0 | 1 | 1 
    6 | 7 | 5 | 300 | 1 | 1 | 1 | 0 
    ................... 
    ................... 
    And so on (rows are manually generated)

Following are my remarks regarding above approach.

Pros:

1. To check if there is no route possible for a given combination check the corresponding edge value for -1 (row 4 and 5 above). One can even count also the number of rows with -1 edge values to know how many route combinations are not possible.

2. To count the total number of route combinations from a multiple routing query, count the total number of rows with reached column value 1. Check also reached column value 1 for the start of a new combination (check row 3 to 4 above).

3. Generating reached column should be easy as all we have to check is if the end_v is either the source or the target value of corresponding edge in a row.

4. Total number of rows will be the total number of edges in a particular route. Unlike -1 placeholder which was consuming one additional last row unnecessarily.

5. While running only one combination (lets say 5-10), if there is no possible route the result will be somewhat similar to this

    `seq | start_v | end_v | edge | direction | cost | tot_cost | reached `
    `-----+---------+-------+------+------+------+----------`
    `0 | 5 | 10 | -1 | 1 | 0 | 1 | 1`

   To deal with condition stated by @dkastl ```For example you may want to join the results with the original table.```, one can easily run a basic SQL like 
    ```with (select * from pgr_djikstra(...) where edge != -1) as result select * from original_table, result where condition```

Cons:

1. I have no idea regarding limitations and possibilities when it comes to real coding. So pardon me.

You are free to completely discard my idea for some logical reasoning.

**Comment by boerngen-schmidt** [comment]
Hello, just to offer another point of view to the problem with the -1 or empty result.

First of I agree with @woodbri on the consistency part of results being returned, so my idea is wrapped around this. When I look at the problem of finding a path I see two basic steps
 1. Calculate the path
 2. Present the result
What I learned from working with various frameworks over the time is, that it is a good design to split these steps, since spliting them offer a number of possibilities which I will try to elaborate.

(magic ball on) When calculating a path from a source to a destination, the result will reside within the memory somehow. This result could be a path or no path. In case of a path there is obiously no problem, in case of no path something has gone wrong. So when calling `pgr_dijkstra` the function could return true or false to indicate if it was successful or not. One problem that I see here is that there might be a partial result in case of multiple sources and destinations, so it might be better to return something like 0 for failure, 1 for success, 2 for partial success. With this output the user is able to choose his approach to present the data.

Presenting the data could the be done for example like this:
```
routing_result = SELECT pgr_dijkstra(...)
if routing_resutl == 1 {
  num_results = SELECT pgr_number_of_results()
  for i <= num_results {
    SELECT pgr_result(i) //pgr_costresult3[] etc.
  }
} else if routing_result == 2 {
  //similar to the way above, but also find out which sources/destionations did not yield a result
} else {
  SELECT pgr_get_error()
}
```

Of course splitting the calculation part and the presentation part does very much alter the product pgrouting, so it must be done carefully. But it also offers a possibility to incorperate nice utility functions, like what the actuall error was on calculating a result for a very specific source/target combination. For me pgrouting is a mere tool to get information about a network and the more functionallity a tool has to give me the answer I need is a great thing. Also thinking about PostgreSQL everything is a transaction, so having multiple steps within a transaction is no problem and the result can still be joined with other data like @dkastl mentioned.
Another possibilty that might open up was the mentioned casting of one result set to another in https://github.com/pgRouting/pgrouting/issues/353#issuecomment-118527769.

I hope I could contribute something to the discussion here without failing to adhere to the consistency of the 'presented' result.

**Comment by cvvergara** [comment]
For  `P(V,E)` to be a path, where `V `is the set of vertices and `E` is the set of edges, some of the conditions are:
```
E != { }
| V | = | E | +1
```
We are giving returning both sets, `V = { node }` and  `E = {edge}` , but a table can not have in one column with `| V |` rows and in another column with `| E |` rows when `| V | != | E |`, so the `-1`  " to indicate the end of the path" is not an element of `E`

There is no path when there is no edge, so returning empty set, is no path.
This path has consists of a single edge:

```
V = {2, 5}
E = { 4(2,5) }   (edge 4 going from 2 to 5)
P(V,E)
```
is represented in a table like this
```
seq | node | edge | cost | tot_cost 
-----+---------+-------+------+------+------+----------
   0 |       2 |    4 |    1 |        0
   1 |  |    5 |   -1 |    0 |        1
```
