### ISSUE TITLE
windows failures on pgRouting 2.0.1

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#411]
Just built on windows building with mingw64 but testing against VC++ PostgreSQL.  I see these two failures.  It's possible they've always been there and since the 2.0 I only ever tested under mingw PostgreSQL I didn't hit them.

One of them looks like we didn't up the version of 2.0.1 on the test?

```
$stats = {
           'doc/test/test.conf' => [
                                     {
                                       'comment' => 'documentation SQL tests for any versions.',
                                       'doc/test/alphashape-any.test' => 'Passed',
                                       'doc/test/analyzeGraph-any.test' => 'Passed',
                                       'doc/test/analyzeOneway-any.test' => 'Passed',
                                       'doc/test/apspJohnson-any.test' => 'Passed',
                                       'doc/test/apspWarshall-any.test' => 'FAILED: 7c7
< 6|1|11|2
---
> 6|1|9|0
9,10c9,10
< 8|1|12|1
< 9|1|13|4
---
> 8|1|11|2
> 9|1|12|1',
                                       'doc/test/astar-any.test' => 'Passed',
                                       'doc/test/bdDijkstra-any.test' => 'Passed',
                                       'doc/test/bdstar-any.test' => 'Passed',
                                       'doc/test/createTopology-any.test' => 'Passed',
                                       'doc/test/createVertTab-any.test' => 'Passed',
                                       'doc/test/dijkstra-any.test' => 'Passed',
                                       'doc/test/drivingDistance-any.test' => 'Passed',
                                       'doc/test/kdijkstra-any.test' => 'Passed',
                                       'doc/test/nodeNetwork-any.test' => 'Passed',
                                       'doc/test/pointsAsPolygon-any.test' => 'Passed',
                                       'doc/test/sampledata.test' => 'Passed',
                                       'doc/test/trsp-any.test' => 'Passed',
                                       'doc/test/tsp-any.test' => 'Passed',
                                       'doc/test/utilities-any.test' => 'FAILED: 1c1
< 2.0.0|pgrouting-2.0.0
---
> 2.0.0|pgrouting-2.0.1'
                                     }
                                   ],

                                     ],
           'z_crash' => 0,
           'z_fail' => 2,
           'z_pass' => 62
         };
```

Seems to be the same issue for all the runs both 32-bit and 64-bit.

**Comment by woodbri** [comment]
The second failure looks like the test result is expecting version 2.0.1 but got 2.0.0, the test result file just needs to be updated for this test because of the version change. I don't know about apspWarshall issue.

**Comment by cvvergara** [comment]
About 2.0.1
Test re-design has to be made for the pgr_version() test.
pgr_aspsWarshall() by it self it has issues:
https://github.com/pgRouting/pgrouting/issues/324
https://github.com/pgRouting/pgrouting/issues/105
And because of all the costs in the documentation sample costs are 1, it can just take any edge.

I tagged master's state as 2.0.1
What it holds is just the minimal changes that occurred in 2 years time.
kind of "save a snapshot of master before releasing 2.1.0"

It so happened that master was disabled in travis so, when those changes happened, no tests were executed. So no one noticed that on Travis for example in postgresql 9.0 there are 27 test failures.
https://travis-ci.org/pgRouting/pgrouting/jobs/79180547#L2675

I would just leave it like that, and put the efforts on the 2.2.0

**Comment by robe2** [comment]
I agree we should worry about 2.1 and 2.2 and this issue doesn't show in 2.1
