### ISSUE TITLE
pgr_dijkstra expects integer source and target instead of bigint

### ISSUE THREAD

**Issue by nextstopsun** [pgRouting/pgrouting#536]
### Expected behavior and actual behavior
According to the doc:
`pgr_dijkstra(text edges_sql, bigint start_vid, bigint end_vid)`
However when source and target in the sql expression (edges_sql argument) are bigint, I get this message:
`ERROR:  Support for id,source,target columns only of type: integer. Support for Cost: double precision` 
When casting to integer query runs with no problems.
So if start_vid and end_vid are bigint, I suppose source and target in sql should also be bigint.
I've got a huge network table and id's are exceeding int4 limit, so I really need them to be bigint.

### Steps to reproduce the problem
Just make a pgr_dijkstra query with bigint source and target in the edges_sql text expression. 

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System
pgr_version output:
`(2.1.0,pgrouting-2.1.0,1,b38118a,master,1.60.0)`
postgis_full_version output:
`POSTGIS="2.2.1 r14555" GEOS="3.5.0-CAPI-1.9.0 r4084" PROJ="Rel. 4.9.2, 08 September 2015" GDAL="GDAL 2.0.2, released 2016/01/26" LIBXML="2.9.3" LIBJSON="0.12" RASTER`
version output:
`PostgreSQL 9.5.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 5.3.0, 64-bit`

Running on Arch Linux OS.

**Comment by cvvergara** [comment]
@nextstopsun 
There two main things to tell:
1) We are on the process of releasing of [pgRotuing V2.2](https://github.com/pgRouting/pgrouting/releases/tag/pgrouting-2.2.0-beta2) so V2.1 will stay as it is.
2) If that problem is on V2.2 I will try to fix it before the final release. 

So trying to reproduce your problem on V2.2:
```
$ createdb doc_data 
$ psql doc_data
psql (9.3.11)
Type "help" for help.

doc_data=# CREATE EXTENSION postgis; CREATE EXTENSION pgrouting;
CREATE EXTENSION
CREATE EXTENSION
doc_data=# SELECT pgr_version();
                     pgr_version                      
------------------------------------------------------
 (2.2.0,pgrouting-2.2.0-beta2,f82dff3,develop,1.54.0)
```
From the [sample data](http://docs.pgrouting.org/v2.2.0-beta2/doc/src/developer/sampledata.html#sample-data):
copy/paste the create table & insert data sections (including creating the topology)

Now lets make the numbers really big:
```
UPDATE edge_table SET source = source*100000000, target = target*100000000;
```

Now run the query:
```
-- no flags (directed flag default is true)
SELECT * FROM pgr_dijkstra(
  'select id,source,target,cost,reverse_cost from edge_table',
  100000000,1100000000);
 seq | path_seq |    node    | edge | cost | agg_cost 
-----+----------+------------+------+------+----------
   1 |        1 |  100000000 |    1 |    1 |        0
   2 |        2 |  200000000 |    4 |    1 |        1
   3 |        3 |  500000000 |   10 |    1 |        2
   4 |        4 | 1000000000 |   12 |    1 |        3
   5 |        5 | 1100000000 |   -1 |    0 |        4
(5 rows)

-- one flag
SELECT * FROM pgr_dijkstra(
  'select id,source,target,cost,reverse_cost from edge_table',
  100000000,1100000000,
  true);
 seq | path_seq |    node    | edge | cost | agg_cost 
-----+----------+------------+------+------+----------
   1 |        1 |  100000000 |    1 |    1 |        0
   2 |        2 |  200000000 |    4 |    1 |        1
   3 |        3 |  500000000 |   10 |    1 |        2
   4 |        4 | 1000000000 |   12 |    1 |        3
   5 |        5 | 1100000000 |   -1 |    0 |        4
(5 rows)
```

To grab the V2.0 functionality that does not accept bigint, its done with 2 flags, in this case things with bigint are errors:
```
SELECT * FROM pgr_dijkstra(
   'select id,source,target,cost,reverse_cost from edge_table',
   100000000,1100000000,
   true,
   true);  -- has_rcost flag does not exist on V2.2 its detected automatically
ERROR:  Error, columns 'source', 'target' must be of type int4, 'cost' must be of type float8
CONTEXT:  PL/pgSQL function pgr_dijkstra(text,integer,integer,boolean,boolean) line 7 at assignment
```

With V2.1:
select pgr_version();
                   pgr_version                   
-------------------------------------------------
 (2.1.0,pgrouting-2.1.0,1,b38118a,master,1.54.0)
(1 row)
 SELECT * FROM pgr_dijkstra(
  'select id,source,target,cost,reverse_cost from edge_table',
   100000000,1100000000);
 seq | path_seq |    node    | edge | cost | agg_cost 
-----+----------+------------+------+------+----------
   1 |        1 |  100000000 |    1 |    1 |        0
   2 |        2 |  200000000 |    4 |    1 |        1
   3 |        3 |  500000000 |   10 |    1 |        2
   4 |        4 | 1000000000 |   12 |    1 |        3
   5 |        5 | 1100000000 |   -1 |    0 |        4
(5 rows)
SELECT * FROM pgr_dijkstra(
  'select id,source,target,cost,reverse_cost from edge_table',
  100000000,1100000000,
  true);
 seq | path_seq |    node    | edge | cost | agg_cost 
-----+----------+------------+------+------+----------
   1 |        1 |  100000000 |    1 |    1 |        0
   2 |        2 |  200000000 |    4 |    1 |        1
   3 |        3 |  500000000 |   10 |    1 |        2
   4 |        4 | 1000000000 |   12 |    1 |        3
   5 |        5 | 1100000000 |   -1 |    0 |        4
```

Again with 2 flags I get  error:
```
 SELECT * FROM pgr_dijkstra(
  'select id,source,target,cost,reverse_cost from edge_table',
  100000000,1100000000,
  true, true);
ERROR:  Support for id,source,target columns only of type: integer. Support for Cost: double precision
CONTEXT:  PL/pgSQL function pgr_dijkstra(text,bigint,bigint,boolean,boolean) line 6 at assignment
```

**Comment by cvvergara** [comment]
Tagged as discussion, because I didn't reproduce the error with out flags in V2.1 or V2.2

**Comment by nextstopsun** [comment]
@cvvergara So is it the last flag that has to be removed for a query to run with no errors? I'm running on a net with no reverse cost.
Does Arch Linux AUR have a pgRouting 2.2 recipe so I can test it?

**Comment by cvvergara** [comment]
@nextstopsun 
Two flags catches the old signature, and you are using bigint, for the old signature that is an error.
The code detects if you are using reverse_cost or not.
I really don't think that  Arch Linux AUR has a pgRouting 2.2 recipe. We are in the re-releases stage, in particular beta2 (some packagers start with alpha and some start at RC1, some others only the final release).

**Comment by nextstopsun** [comment]
@cvvergara Looks like bi-directional algorithms also lack support for bigint id's. Tried with bdDijkstra - no luck at all.

**Comment by cvvergara** [comment]
@nextstopsun 
Just some history:
v2.0 objective was to reorganize the existing code, fix some obvious bugs, create some topology functions, and the pgr_trsp
None of the v2.0 accept bigints. read #140

So we are transitioning gradually to 3.0 where hopefully all functions can use bigint's as id's (and on the way, fix the bugs)

So we are talking about:
1) migrating code written in c++98 to be c++11
2) migrating types where applicable
3) create unit tests on all functions (find all the bugs)
4) decision making of complete rewrite or just change types of functions based on unit tests
5) think beyond... how to setup pgRouting so that additional functionality is done "easily"  or code rewrite is done "easily" ("easy" = what is easy for you it might not be easy for me.)
6) modify the pgrRoutingLayer plugin for Qgis
7) change the documentation
8) Work on the translations. 
9) Change workshop
10) keep the old functionality during 2.x (with the int signature so to not break code of people who already coded using that signature)

And above all we are talking of [graph algorithms](https://en.wikipedia.org/wiki/Category:Graph_algorithms) that might not be obvious on how to code. 

v2.0 came out on September 2013, v2.1 was on September 2015
So after 2 years of research and hard work we finally got out the first changes
pgr_dijkstra, pgr_ksp, pgr_drivingDistance
We had to decide if we change all existing code for the next release or make smaller releases but more often. We decided for the later. (fix some functions & add some functionality in each new release)

Now 1/2 year+-   v2.2 comes out with more changes.
pgr_floydWarshall, pgr_Johnson, pgr_dijkstraCost and
add withPoints family of functions (as proposed functions for 2.3, but already there)
