### ISSUE TITLE
Cleaning up the Wiki

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#581]
There are currently 181 Wiki pages, which need a major review and cleanup.

- [ ] Identify outdated information
- [ ] Group by topics
- [ ] Create links between pages
- [ ] Use the Github "Sidebar" better
- [ ] Use the Github "Footer" for some quick links as well

**Comment by cvvergara** [comment]
I think this is outdated
https://github.com/pgRouting/pgrouting/wiki/APSP  -- (pgr_johnson and pgr_floydWarshall)

And maybe the https://github.com/pgRouting/pgrouting/wiki#algorithms section can have another name or maybe moved to gsoc section as subsection "Possible algorithms", because besides:
Turn Restricted Shortest Path (TRSP) -- is a "how to" of an implemented function
All Pairs Shorest Path (APSP)  -- (pgr_johnson and pgr_floydWarshall)

And maybe have a section "How to" where to put the links to:
Turn Restricted Shortest Path (TRSP)
https://github.com/pgRouting/pgrouting/wiki/TRSP-for-railroads
https://github.com/pgRouting/pgrouting/wiki/Create-Topology-With-Z-Levels-at-Intersections
etc.
