### ISSUE TITLE
Sphinx Bootstrap Theme

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#638]
While I found the current Sphinx theme nice a few years ago, I don't like it anymore now. But I don't like the default Sphinx theme either.

However, I just found out about a "Sphinx Bootstrap Theme", which can be installed as Ubuntu package with at least 16.04: http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html

You can easily switch to other designs: http://bootswatch.com/

This might also worth to consider for pgRouting workshop and website.

Thoughts? 
Volunteers?

**Comment by cvvergara** [comment]
Here is my thought:
- I don't like the current one, never did (too much orange).
- I would leave the change of theme, in the documentation, to the next mayor release
-  All other places like the website / workshop  that already use sphinx can start changing
- Also, pgRoutingLayer and osm2pgrouting that don't have  a formal documentation page, just a wiki for documentation can start using sphinx with what ever is decided.

The other thing that I would like is to"flatten" the pgRouting's documentation, what do I mean for that:
without loosing the tree structure, for example:
```
src/allpairs/doc/pgr_johnson.rst
src/allpairs/doc/pgr_floydWarshall.rst
src/dijkstra/doc/pgr_dijkstra.rst
```
instead of generating the web pages following the tree structure like we do now:
```
http://docs.pgrouting.org/2.2/en/src/allpairs/doc/pgr_johnson.html
http://docs.pgrouting.org/2.2/en/src/allpairs/doc/pgr_floydWarshall.html
http://docs.pgrouting.org/2.2/en/src/dijsktra/doc/pgr_dijkstra.html
```
Generate them like:
```
http://docs.pgrouting.org/2.2/en/pgr_johnson.html
http://docs.pgrouting.org/2.2/en/pgr_floydWarshall.html
http://docs.pgrouting.org/2.2/en/pgr_dijkstra.html
```
That way, if a user arrives to the documentation say to:
```
http://docs.pgrouting.org/2.2/en/pgr_johnson.html
```
And wants to use pgr_dijkstra
he can just edit the function name in the navigation bar.
Currently that is not possible because the change in directory.
So all functions are at the same level, (that is what I mean by "flatten")
```
http://docs.pgrouting.org/2.2/en/pgr_FOO.html
http://docs.pgrouting.org/2.2/en/pgr_BAR.html
```

**Comment by dkastl** [comment]
Let's make this a task for v3.0 ... it's not urgent anyway.

**Comment by cvvergara** [comment]
I think the theme we are using now since some time is OK
The theme that is used by packagers is still the orange one, the one we use has more dependencies, so to avoid packagers more dependencies we are ok.
