### ISSUE TITLE
rows_where failure with pgr_createVerticesTable

### ISSUE THREAD

**Issue by GGummow** [pgRouting/pgrouting#683]
### Expected behavior and actual behaviour
I've noded a network (pgr_nodeNetwork) then created a topology (pgr_createTopology) and then wanted to modify the Vertex table only for sectioned analysis (pgr_createVerticesTable) using rows_where:='selection_for_true' and I think there's a bug.

SELECT pgr_createVerticesTable('my_noded_topology');   -- works
SELECT pgr_createVerticesTable('my_noded_topology', rows_were:='true');   -- failed
SELECT pgr_createVerticesTable('my_noded_topology', rows_were:='TRUE');   -- works
SELECT pgr_createVerticesTable('my_noded_topology', rows_were:='1=1');   -- failed
SELECT pgr_createVerticesTable('my_noded_topology', rows_were:='my_boolean_criterion');   -- failed
SELECT pgr_createTopology('my_noded_topology', 0.001, rows_were:='my_boolean_criterion');   -- is ok

Note that I've define 'works' as a populated my_noded_topology_vertices_pgr table, and 'failed' as an empty table.

### My guess on Steps to resolve the problem
It seems as though the function is receiving uppercase bool and requires lowercase 

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Win7 64bit   "PostgreSQL 9.5.4, compiled by Visual C++ build 1800, 64-bit"
"POSTGIS="2.2.2 r14797" GEOS="3.5.0-CAPI-1.9.0 r4090" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.0.2, released 2016/01/26" LIBXML="2.7.8" LIBJSON="0.12" RASTER"
 "(2.2.2,pgrouting-2.2.2,544044b,master,1.59.0)"
`

**Comment by cvvergara** [comment]
@GGummow 

Making sure I undertsand the problem:

-  pgr_nodeNetwork is not the current problem. (regardless that pgr_nodeNetwork by itself its buggy and its pending for the rewrite)
  - Note that pgr_nodeNetwork had a regression error #612 that was fixed on 2.2.4 (you are using 2.2.2)
- This issue is only about pgr_createVerticesTable 

I'll make tests on  pgr_createVerticesTable based on your queries:
- all queries should work on a fixed code

**Comment by GGummow** [comment]
Correct, I've just updated due to #612 , NOTE: Since posting the problem has stopped, I'll keep chasing to see if something else is going on (e.g. some side effect to the source and target data in my edges table).

I'll repost later today, or have the ticket withdrawn if it looks like the bug is related to my code.

**Comment by cvvergara** [comment]
@GGummow 
```
SELECT pgr_createVerticesTable('my_noded_topology', rows_were:='1=1'); -- failed
```
I think that should work on all rows because `1=1` is true on all rows, but I still need to make test using the sample data.

BTW 2.3.0 is ready (the packages will come out on Thursday Sep 29, when postgres 9.6 & postGIS 2.3 are also packaged)

Forgot to mention:
- in 3.0 its a complete rewrite of this function (and the other topology functions)

**Comment by cvvergara** [comment]
@GGummow

the queries you wrote have
```
rows_were:= 
```
instead of
```
rows_where:=
```

here is a test:
```
SELECT pgr_createVerticesTable('edge_table', rows_where:='1=1');
NOTICE:  PROCESSING:
NOTICE:  pgr_createVerticesTable('edge_table','the_geom','source','target','1=1')
NOTICE:  Performing checks, please wait .....
NOTICE:  Populating public.edge_table_vertices_pgr, please wait...
NOTICE:    ----->   VERTICES TABLE CREATED WITH  17 VERTICES
NOTICE:                                         FOR   18  EDGES
NOTICE:    Edges with NULL geometry,source or target: 0
NOTICE:                              Edges processed: 18
NOTICE:  Vertices table for table public.edge_table is: public.edge_table_vertices_pgr
NOTICE:  ----------------------------------------------
 pgr_createverticestable 
-------------------------
 OK
(1 row)
```

**Comment by GGummow** [comment]
Think there was something unstable on my machine after upgrade. Reboot & Vacuum, seems ok, pretty sure it wasn't a were/where thing, but who knows? Cheers.
