### ISSUE TITLE
pgr_trsp do not return anything on same edge search

### ISSUE THREAD

**Issue by juliensam** [pgRouting/pgrouting#693]
### Expected behavior and actual behavior

When doing a pgr_trsp query where the same edge is being used for start and end search, no route is returned. In my case, the edge in question is a big loop that goes around a peninsula and the shortest path between the start and the end of this segment would go through another edge.
### Steps to reproduce the problem

```
create table routing (gid serial, length integer, source integer, target integer, reverse_cost integer);
insert into routing (length, source, target, reverse_cost) values
 (10000, 1, 2, 10000),
 (5, 3, 1, 5),
 (10, 4, 3, 10),
 (10, 2, 4, 10);
```

pgRouting 2.1.0:

```
select pgr_trsp(
  'SELECT gid as id, source::int4, target::int4, length::float8 as cost, length::float8 as reverse_cost FROM routing', 
  1, 0.1, 1, 0.9, false, true
);
 seq | id1 | id2 | cost 
-----+-----+-----+------
   0 |  -1 |   1 | 1000
   1 |   1 |   2 |    5
   2 |   3 |   3 |   10
   3 |   4 |   4 |   10
   4 |   2 |   1 | 1000
```

pgRouting 2.2.3:

```
select pgr_trsp(
  'SELECT gid as id, source::int4, target::int4, length::float8 as cost, length::float8 as reverse_cost FROM r ', 
  1, 0.1, 1, 0.9, false, true
);
WARNING:  transaction left non-empty SPI stack
HINT:  Check for missing "SPI_finish" calls.
 pgr_trsp 
----------
(0 rows)
```
### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Ubuntu 14.04
Use the commands:

```
SELECT version();
 PostgreSQL 9.3.14 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

SELECT postgis_full_version();
 POSTGIS="2.1.2 r12389" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.1, released 2013/08/26" LIBXML="2.9.1" LIBJSON="UNKNOWN" RASTER


SELECT pgr_version();
 (2.2.3,pgrouting-2.2.3,6d05b9b,master,1.54.0)

```

**Comment by dkastl** [comment]
Julien, thanks for reporting. Am I correct, that it worked in 2.1 but not anymore in the latest version?

**Comment by cvvergara** [comment]
@juliensam 

Is this what you want as result?

```
SELECT * FROM pgr_withpoints(
  'SELECT gid as id, source, target, length as cost, length as reverse_cost FROM routing', 
  '(SELECT 1 as pid, 1 as edge_id, 0.1::float as fraction) union (SELECT 2 , 1, 0.9)',
-1, -2);
 seq | path_seq | node | edge | cost | agg_cost 
-----+----------+------+------+------+----------
   1 |        1 |   -1 |    1 | 1000 |        0
   2 |        2 |    1 |    2 |    5 |     1000
   3 |        3 |    3 |    3 |   10 |     1005
   4 |        4 |    4 |    4 |   10 |     1015
   5 |        5 |    2 |    1 | 1000 |     1025
   6 |        6 |   -2 |   -1 |    0 |     2025
(6 rows)
```

shorter version because its based on length, so using unidrected graph:

```
SELECT * FROM pgr_withpoints(
  'SELECT gid as id, source, target, length as cost FROM routing', 
  '(SELECT 1 as pid, 1 as edge_id, 0.1::float as fraction) union (SELECT 2 , 1, 0.9)',
-1, -2, directed:=false);
 seq | path_seq | node | edge | cost | agg_cost 
-----+----------+------+------+------+----------
   1 |        1 |   -1 |    1 | 1000 |        0
   2 |        2 |    1 |    2 |    5 |     1000
   3 |        3 |    3 |    3 |   10 |     1005
   4 |        4 |    4 |    4 |   10 |     1015
   5 |        5 |    2 |    1 | 1000 |     1025
   6 |        6 |   -2 |   -1 |    0 |     2025
(6 rows)
```

**Comment by cvvergara** [comment]
negative numbers on the result represent pids so:
node: -1 & -2 in the result are the pids

**Comment by cvvergara** [comment]
Regression error

**Comment by cvvergara** [comment]
```
SELECT * from pgr_trsp(
  'SELECT gid as id, source::int4, target::int4, length::float8 as cost, length::float8 as reverse_cost FROM routing', 
  1, 0.1, 1, 0.9, false, true
);
 seq | id1 | id2 | cost 
-----+-----+-----+------
   0 |  -1 |   1 | 1000
   1 |   1 |   2 |    5
   2 |   3 |   3 |   10
   3 |   4 |   4 |   10
   4 |   2 |   1 | 1000
   5 |  -2 |  -1 |    0
(6 rows)
```

should be the result.

**Comment by juliensam** [comment]
This is indeed what I expect and yes it was working with pgRouting 2.1 and not anymore with 2.2.3. Thank you very much!

The pgr_withpoints method return what I expected. Let me know if I can provide anyn help to fix this issue.

**Comment by cvvergara** [comment]
What can I tell you:
As long as you are not using restrictions you can use the With Points family of functions. (the column names are nicer)

I Forgot to make the wrapper on that function when there are no restrictions. (that is if no restrictions then I am wrapping for using withPoints )

But the trsp still has the regression error and Its all my fault ...
I also made some changes on the C/C++ code, but I might have changed something I shouldn't have changed.

**Comment by woodbri** [comment]
TRSP and generalized support turn restrictions is in Vicky's queue to be rewritten. I'm not sure spending a lot of time on this issue know is worthwhile considering the planned rewrite. I believe Vicky is working on updating osm2pgrouting so it can extract relationships like turn restrictions which is a precursor to the rewrite.

**Comment by juliensam** [comment]
No rush, we are not using turn restriction right now. I was using it to be able to query by edge. Don't be too hard on you cvvergara, we all make mistakes. This one is not bad at all sinnce it has been there for so many months. :)

**Comment by cvvergara** [comment]
The example shown would still have the problem if turn restrictions where added in the query.
which makes it a Regression error. Even if I add the wrapper I forgot, to use pgr_withPoints when no restrictions are given.

Adding the missing wrapper, and reverting to the old code, clearly (at least for me) I failed to fix all this: (showing all warnings, what is a warning in one compiler is an error in other compiler) 
https://travis-ci.org/cvvergara/pgrouting/jobs/173621027#L675
As I broke code somewhere somehow trying to fix them and improve code.

Even with all those warnings still work on travis & jenkins but unfortunately **fails** on appveyor.

Travis, (linux precise & trusty)  all test pass
Added the wrapper:
[Test file](https://github.com/cvvergara/pgrouting/blob/fix/issue693/src/trsp/test/issue693.test.sql)
[expected result file](https://github.com/cvvergara/pgrouting/blob/fix/issue693/src/trsp/test/issue693.result)
[test pass](https://travis-ci.org/cvvergara/pgrouting/jobs/173621027#L1203)

On Jenkins (for the windows binaries) looks like the warnings does not affect it for example this execution (release mode: compilation with out the show all warnings flag):
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_PGVersionEDB/5440/console

**Fails** on appveyor (vs2013) (release mode: compilation with out the show all warnings flag):
https://ci.appveyor.com/project/cvvergara/pgrouting/build/2.3.435#L1139

The trsp code is buggy but at least gives some results that follow restrictions. My try to fix some bugs added other bugs that generated this issue (and who knows what else)

So I mention 2 alternatives for "fixing" this Regression Bug and get the same passing results as in the tests:
Option 1)
  - Just add the wrapper I forgot to add. and live with the Regression Bug
Option 2)
  - Fix the warnings but this time without trying to improve the code (aka to avoid adding my own bugs), not so easy because of [this kind of errors](https://ci.appveyor.com/project/cvvergara/pgrouting/build/2.3.435#L1143),  but this option will fix the regression error. (the original logical bugs will remain)

Personally I like option (2) the reason is:
I am working right now on osm2pgrouting where one of the purposes is to get the restrictions on the osm data, once I have that information I can rewrite the trsp code starting from scratch.
I don't feel that I will have time to finish for the next release minor of pgRouting (2.4),  so, fixing this regression bug is worth because the same code will be used in 2.4.

**Comment by cvvergara** [comment]
(option 2)
Fixed all warnings & in all three CI tests works:
https://travis-ci.org/cvvergara/pgrouting/builds/173793546
https://ci.appveyor.com/project/cvvergara/pgrouting/build/2.3.452
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_matrix_cvvergara_repo/69/

**Comment by juliensam** [comment]
@cvvergara you are the best! If you are planning major rewrite of the function, option 2 is indeed the best one, but as I said, we do have an alternative with  the pgr_withPoints. If the fix is too complex, don't spend too much time on this.

**Comment by cvvergara** [comment]
@juliensam 

> you are the best!
thanks

> If you are planning major rewrite of the function

its being on the plan since the rewrite of all pgRouting started ;)
But as I mentioned this time comes osm2pgRouting first to be able to have some "data" grounds

> alternative with the pgr_withPoints

As long as not using restrictions is the alternative.

> If the fix is too complex, don't spend too much time on this.

I didn't plan to take more than 3 days, to revert the code, fixed the warnings & executions problems & add the wrapper I forgot.
took me 2. So don't worry.
when the changes get approved, making the release will take me also a couple of days ... maybe next weekend

Thanks for caring
