### ISSUE TITLE
pgr_dijkstra working, but cannot get pgr_kdijkstraPath to work

### ISSUE THREAD

**Issue by JLErvin** [pgRouting/pgrouting#777]
Hello, 

I am able to get pgRouting to work with pgr_dijkstra. In my psql database I can successfully run: 

`SELECT seq, node, edge, cost FROM pgr_dijkstra('SELECT gid as id, source, target,length as cost FROM ways',100, 500, false);`

However, I do not just want to calculate the distance between two nodes. I want to be able to take one node, and find the nearest node from a set of destination nodes. I have tried to use pgr_kdijkstraPath to no avail. Here is the code that does not work. 

`SELECT seq, node, edge, cost FROM pgr_kdijkstraPath('SELECT gid as id, source, target,length as cost FROM ways',100, array[10,20], false,false);`

This returns the following result: 

`ERROR: column "node" does not exist"`

This is confusing, because it does not seem like there should be any difference between the two. 

I am currently running:
PostgresSQL 9.5.6
PostGIS 2.3.3
pgRouting 2.1.0
Ubuntu 16.04

**Comment by dkastl** [comment]
Well, if you run the function with `*` instead of `seq, node, edge, cost`, you will see all columns returned and the error should go away.

```
SELECT * FROM pgr_kdijkstraPath(
    'SELECT gid as id, source, target,length as cost FROM ways',
    100, array[10,20], false,false
);
```
`pgr_kdijkstraPath` returns different set of attributes than `pgr_dijkstra`.

**Comment by JLErvin** [comment]
I am still getting an error: 

`ERROR:  Error, columns 'source', 'target' must be of type int4, 'cost' must be of type float8`

**Comment by cvvergara** [comment]
Hello @JLErvin 

I see you are using pgRouting Version 2.1. You must have your reasons of doing that. I strongly recommend that you use the latest version, currently is [V2.4.](http://docs.pgrouting.org/2.4/en/index.html)

this is wrong:
```
SELECT seq, node, edge, cost 
FROM pgr_kdijkstraPath(
'SELECT gid as id, source, target,length as cost FROM ways',
100, array[10,20], false,false);
```


In version 2.0 & 2.1:
- The function's inner query are used with INTEGER data types  `columns 'source', 'target' must be of type int4`
- the message does not mention id, the code does not check that column and does not complain about it, but internally it is an int4, so if you have id with bigint values you will get wierd "id" values in the result.
-  pgr_kdijkstraPath returns pgr_costResult3[] it does not returns seq, node, edge, cost
- the code had a lot of issues so the results are not correct


Please read the  [kdijkstra](http://docs.pgrouting.org/2.1/en/src/kdijkstra/doc/index.html) dpcumentation and the [pgr_costResult3](http://docs.pgrouting.org/2.1/en/src/common/doc/types/cost_result.html#type-cost-result3) documentation
The pgr_kdijkstraPath and pgr_kdijkstraCost are deprecated since v2.2, see the [changelog](http://docs.pgrouting.org/2.4/en/release_notes.html#changelog-2-2-0)

On V2.1, you can use the  [pgr_dijkstra(one to many)](http://docs.pgrouting.org/2.1/en/src/dijkstra/doc/dijkstra_v3.html#signatures) instead of  pgr_kdijkstraPath

So instead of this:
```
SELECT * FROM pgr_kdijkstraPath(
    'SELECT gid::INTEGER as id, source::INTEGER, target::INTEGER, length::FLOAT as cost
     FROM ways',
    100, array[10,20], false,false
);
```

use this:
```
SELECT * FROM pgr_dijkstra(
    'SELECT gid as id, source, target, length as cost FROM ways',
    100, array[10,20], directed:=false
);
```

I am closing this issue because `pgr_kdijkstraPath` was deprecated on V2.2 and the current version is V2.4.
