### ISSUE TITLE
ERROR: Couldn't open a connection to SPI

### ISSUE THREAD

**Issue by GeoCastello** [pgRouting/pgrouting#861]
Hi Everybody,

I'm having a problem when using pgrouting and I'm not able to understand what's going on.

I'm computing all shortest paths between all pair of points of my network. This works fine in one dataset I used for testing. But now, I'm using a new dataset (like double size), and it crashes showing me the error:

ERROR: Couldn't open a connection to SPI

This is the log file:
2017-06-22 18:25:23 CEST [3090-1] postgres@testimports ERROR: Couldn't open a connection to SPI
2017-06-22 18:25:23 CEST [3090-2] postgres@testimports STATEMENT: DROP TABLE IF EXISTS routes_generated;
CREATE TABLE routes_generated (gid serial primary key, source text, target text, geom geometry('GEOMETRY', 3857));
INSERT INTO routes_generated (source, target, geom) SELECT r1.source_name, r1.target_name, st_linemerge((SELECT st_linemerge(st_union(b.the_geom)) as the_geom FROM pgr_trsp('SELECT gid::INTEGER AS id, source::INTEGER, target::INTEGER, cost FROM ways', r1.source_id, r1.source_pos, r1.target_id, r1.target_pos, false, false) a, ways b WHERE a.id2=b.gid)) FROM train_stations_comb_id2 r1;

I would really apreciate any help you could give me!

Thank you very much in advance.

**Comment by cvvergara** [comment]
I dont know which version of pgrouting you are using.
I dont know which version of postgres you are using.
What I do know is you are using pgr_trsp.
https://github.com/pgRouting/pgrouting/tree/master/src/trsp/doc
https://github.com/pgRouting/pgrouting/wiki/Notes-on-pgr_trsp--(2.3.2-release)

**Comment by GeoCastello** [comment]
Sorry, I'm using PostgreSQL 9.5.7 and pgrouting 2.2.3

**Comment by cvvergara** [comment]
@GeoCastello 

If you can change to the latest pgRouting would be better.
I can't remember when pgRouting got the fix for it to work on postgresl 9.5, but on pgRouting 2.4.1 there haven't being complains about SPI.
That does not change the fact that pgr_trsp still has bugs (we are still working on it).
Haven't heard of it producing a segmentation fault on 2.4.1, so it looks like it does not crash the server.
Consider the results as approximations.

**Comment by StianOvrevage** [comment]
I'm getting 

```
psycopg2.InternalError: Couldn't open a connection to SPI
CONTEXT:  SQL function "pgr_drivingdistance" statement 1
```

Running on AWS Aurora with following versions:

```
PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit
pgrouting: 2.4.2
postgis: 2.3.4
```

**Comment by dkastl** [comment]
@StianOvrevage , do you mean, that you're working on the same case as @GeoCastello and solved the problem? In that case, can you please close the issue? Thank you.

**Comment by StianOvrevage** [comment]
I don't think so.

His problem is apparently the dataset was too large. My problem was I used an empty dataset. The error message is the same though.

**Comment by cvvergara** [comment]
Work has been done for TRSP on develop branch for version 3.4 (due to be released on September/October 2022:
https://github.com/pgRouting/pgrouting/issues/2238
Please check the documentation
https://docs.pgrouting.org/dev/en/TRSP-family.html
and the migration guide:
https://docs.pgrouting.org/dev/en/trsp_migration.html

For further similar problems with TRSP functions please open a new issue with the specific function name.
